<footer>
<div id="footer-container">
    <section id="site-legal">
        <p><a href="/admin"><em>log in</em></a></p>
        <p>copyright <?= date('Y') ?><br />weston fribley</p>
    </section>
    <section id="site-info">
        <p>This site was designed by me, with some help from <a href="http://twitter.github.com/bootstrap/" title="Bootstrap, from Twitter"><em>Bootstrap</em></a>.</p>
        <p>It is built on my own custom<br />blogging CMS called "Hedgehog."
            <br />(v2.0)
        </p>
    </section>
</div>
</footer>

</html>